# Generated by Django 3.2.9 on 2021-11-04 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopeapp', '0002_alter_product_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(max_length=50),
        ),
    ]
