# Generated by Django 3.2.9 on 2021-11-04 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopeapp', '0006_alter_cart_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.AddField(
            model_name='cart',
            name='product_id',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='shopeapp.product'),
        ),
    ]
